project_id = "heupadftmypiolkatzkg"

[functions.fix-ish-chat]
verify_jwt = false

[functions.n8n_bridge]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false
